# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05a078a6ffc1c0e55ff8ced667b11b734a5dcf634cce4ef896af1b2e63858da6ae1d112f6012a7db915bfc56e47730a3a1354d979974494cddf0e25bd0732123

test:
  secret_key_base: e262c2c73a459c34d8a4d6e742748e073873ed4a062f4fe00357b9e4701c6d45415a0618ad11a2af3b17686ed54259372792090d18d376c4070c1a07552efcc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
